<?php

declare(strict_types=1);

namespace App\Domain\Entities;

use Doctrine\ORM\Mapping as ORM;
use DateTimeImmutable;

#[ORM\Entity]
#[ORM\Table(name: 'Task')]
class Task
{
    #the task ID which is autogenerated by MariaDB
    #[ORM\Id]
    #[ORM\Column(type: 'integer', unique: true)]
    #[ORM\GeneratedValue]
    private ?int $id;

    #the title of the task at hand
    #[ORM\Column(type: 'string', length: 15, nullable: false)]
    private string $title;

    #The limit date for the task, it uses a PHP implementation of DateTimeImmutable
    #[ORM\Column(type: 'datetime_immutable')]
    private DateTimeImmutable $limitDate;


    #the title of the task at hand
    #[ORM\Column(type: 'string')]
    private string $description;


}